apiVersion: 1

datasources:
  - name: TradingDB
    type: postgres
    uid: trading_postgres
    url: trading_postgres:5432
    user: tei_user
    secureJsonData:
      password: TEI@2026
    jsonData:
      database: tei2026
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true